// Theme presets and color palettes for the Linktree clone

export const THEME_PRESETS = [
  {
    id: "default",
    name: "Default Purple",
    preview: "linear-gradient(135deg, #6366F1 0%, #A855F7 100%)",
    page_bg_type: "gradient",
    page_bg_gradient_from: "#6366F1",
    page_bg_gradient_to: "#A855F7",
    card_bg_color: "#FFFFFF",
    card_text_color: "#1F2937",
  },
  {
    id: "midnight",
    name: "Midnight Blue",
    preview: "linear-gradient(135deg, #1E3A8A 0%, #312E81 100%)",
    page_bg_type: "gradient",
    page_bg_gradient_from: "#1E3A8A",
    page_bg_gradient_to: "#312E81",
    card_bg_color: "#1E293B",
    card_text_color: "#F1F5F9",
  },
  {
    id: "sunset",
    name: "Sunset Orange",
    preview: "linear-gradient(135deg, #F97316 0%, #EC4899 100%)",
    page_bg_type: "gradient",
    page_bg_gradient_from: "#F97316",
    page_bg_gradient_to: "#EC4899",
    card_bg_color: "#FFFFFF",
    card_text_color: "#1F2937",
  },
  {
    id: "forest",
    name: "Forest Green",
    preview: "linear-gradient(135deg, #059669 0%, #0D9488 100%)",
    page_bg_type: "gradient",
    page_bg_gradient_from: "#059669",
    page_bg_gradient_to: "#0D9488",
    card_bg_color: "#ECFDF5",
    card_text_color: "#064E3B",
  },
  {
    id: "ocean",
    name: "Ocean Blue",
    preview: "linear-gradient(135deg, #0EA5E9 0%, #06B6D4 100%)",
    page_bg_type: "gradient",
    page_bg_gradient_from: "#0EA5E9",
    page_bg_gradient_to: "#06B6D4",
    card_bg_color: "#F0F9FF",
    card_text_color: "#0C4A6E",
  },
  {
    id: "rose",
    name: "Rose Pink",
    preview: "linear-gradient(135deg, #F43F5E 0%, #EC4899 100%)",
    page_bg_type: "gradient",
    page_bg_gradient_from: "#F43F5E",
    page_bg_gradient_to: "#EC4899",
    card_bg_color: "#FFF1F2",
    card_text_color: "#881337",
  },
  {
    id: "dark",
    name: "Dark Mode",
    preview: "linear-gradient(135deg, #18181B 0%, #27272A 100%)",
    page_bg_type: "gradient",
    page_bg_gradient_from: "#18181B",
    page_bg_gradient_to: "#27272A",
    card_bg_color: "#3F3F46",
    card_text_color: "#FAFAFA",
  },
  {
    id: "lavender",
    name: "Lavender Dream",
    preview: "linear-gradient(135deg, #A78BFA 0%, #C4B5FD 100%)",
    page_bg_type: "gradient",
    page_bg_gradient_from: "#A78BFA",
    page_bg_gradient_to: "#C4B5FD",
    card_bg_color: "#F5F3FF",
    card_text_color: "#4C1D95",
  },
  {
    id: "minimalist",
    name: "Minimalist White",
    preview: "#F9FAFB",
    page_bg_type: "color",
    page_bg_color: "#F9FAFB",
    page_bg_gradient_from: "#F9FAFB",
    page_bg_gradient_to: "#F9FAFB",
    card_bg_color: "#FFFFFF",
    card_text_color: "#111827",
  },
  {
    id: "neon",
    name: "Neon Nights",
    preview: "linear-gradient(135deg, #7C3AED 0%, #F472B6 100%)",
    page_bg_type: "gradient",
    page_bg_gradient_from: "#7C3AED",
    page_bg_gradient_to: "#F472B6",
    card_bg_color: "#1F1F1F",
    card_text_color: "#F472B6",
  },
  {
    id: "autumn",
    name: "Autumn Warmth",
    preview: "linear-gradient(135deg, #DC2626 0%, #F59E0B 100%)",
    page_bg_type: "gradient",
    page_bg_gradient_from: "#DC2626",
    page_bg_gradient_to: "#F59E0B",
    card_bg_color: "#FFFBEB",
    card_text_color: "#78350F",
  },
  {
    id: "custom",
    name: "Custom",
    preview: "linear-gradient(135deg, #6366F1 0%, #A855F7 100%)",
    page_bg_type: "gradient",
    page_bg_gradient_from: "#6366F1",
    page_bg_gradient_to: "#A855F7",
    card_bg_color: "#FFFFFF",
    card_text_color: "#1F2937",
  },
];

export const COLOR_PALETTES = [
  {
    name: "Basic",
    colors: ["#000000", "#FFFFFF", "#F3F4F6", "#E5E7EB", "#9CA3AF", "#6B7280", "#4B5563", "#374151", "#1F2937", "#111827"],
  },
  {
    name: "Vibrant",
    colors: ["#EF4444", "#F97316", "#F59E0B", "#EAB308", "#84CC16", "#22C55E", "#10B981", "#14B8A6", "#06B6D4", "#0EA5E9"],
  },
  {
    name: "Cool",
    colors: ["#3B82F6", "#6366F1", "#8B5CF6", "#A855F7", "#D946EF", "#EC4899", "#F43F5E", "#0891B2", "#0D9488", "#059669"],
  },
  {
    name: "Pastel",
    colors: ["#FEE2E2", "#FFEDD5", "#FEF3C7", "#FEF9C3", "#ECFCCB", "#D1FAE5", "#CCFBF1", "#CFFAFE", "#DBEAFE", "#E0E7FF"],
  },
  {
    name: "Dark",
    colors: ["#18181B", "#27272A", "#3F3F46", "#52525B", "#71717A", "#1E293B", "#334155", "#475569", "#64748B", "#94A3B8"],
  },
];

export const FONT_OPTIONS = [
  { value: "sans", label: "Sans Serif", class: "font-sans", preview: "Aa" },
  { value: "serif", label: "Serif", class: "font-serif", preview: "Aa" },
  { value: "mono", label: "Monospace", class: "font-mono", preview: "Aa" },
];

export const CARD_STYLES = [
  { value: "filled", label: "Filled", description: "Solid background color" },
  { value: "outline", label: "Outline", description: "Transparent with border" },
  { value: "shadow", label: "Shadow", description: "Elevated with shadow" },
  { value: "glass", label: "Glass", description: "Frosted glass effect" },
];

export const BORDER_RADIUS_OPTIONS = [
  { value: "none", label: "Square", class: "rounded-none" },
  { value: "sm", label: "Slight", class: "rounded-lg" },
  { value: "rounded", label: "Rounded", class: "rounded-xl" },
  { value: "full", label: "Pill", class: "rounded-full" },
];

export const ICON_OPTIONS = [
  { value: "", label: "No Icon" },
  { value: "link", label: "Link" },
  { value: "globe", label: "Globe" },
  { value: "mail", label: "Email" },
  { value: "phone", label: "Phone" },
  { value: "twitter", label: "Twitter/X" },
  { value: "instagram", label: "Instagram" },
  { value: "youtube", label: "YouTube" },
  { value: "tiktok", label: "TikTok" },
  { value: "linkedin", label: "LinkedIn" },
  { value: "github", label: "GitHub" },
  { value: "spotify", label: "Spotify" },
  { value: "discord", label: "Discord" },
  { value: "twitch", label: "Twitch" },
  { value: "shopping", label: "Shopping" },
  { value: "document", label: "Document" },
  { value: "calendar", label: "Calendar" },
  { value: "heart", label: "Heart" },
  { value: "star", label: "Star" },
  { value: "music", label: "Music" },
  { value: "whatsapp", label: "WhatsApp" },
  { value: "telegram", label: "Telegram" },
  { value: "facebook", label: "Facebook" },
  { value: "pinterest", label: "Pinterest" },
  { value: "snapchat", label: "Snapchat" },
];
